name: .NET Build Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Action pré-existente para verificar o código do repositório
    - name: Checkout repository
      uses: actions/checkout@v4  # Atualizado para usar Node.js 20

    # Configurar o .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4  # Atualizado para usar Node.js 20
      with:
        dotnet-version: '6.0.x'

    # Navegar para o diretório do projeto
    - name: Navigate to project directory
      run: cd github4women

    # Restaurar dependências do .NET
    - name: Restore dependencies
      run: dotnet restore

    # Build do projeto
    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    # Executar testes (script personalizado)
    - name: Run tests
      run: |
        echo "Running tests..."
        dotnet test --no-restore --verbosity normal

    # Rodar o webapp
    - name: Run webapp
      run: dotnet run --project github4women.csproj
