name: .NET Build Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Action pré-existente para verificar o código do repositório
    - name: Checkout repository
      uses: actions/checkout@v4  # Atualizado para usar Node.js 20

    # Configurar o .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4  # Atualizado para usar Node.js 20
      with:
        dotnet-version: '6.0.x'

    # Restaurar dependências do .NET
    - name: Restore dependencies
      working-directory: ./github4women
      run: dotnet restore

    # Build do projeto
    - name: Build the project
      working-directory: ./github4women
      run: dotnet build --configuration Release --no-restore

    # Executar testes (script personalizado)
    - name: Run tests
      working-directory: ./github4women
      run: |
        echo "Running tests..."
        dotnet test --no-restore --verbosity normal

    # Rodar o webapp e verificar se ele inicia corretamente
    - name: Start and verify webapp
      working-directory: ./github4women
      run: |
        echo "Starting webapp..."
        dotnet run --no-build --project github4women.csproj &
        sleep 10
        if curl -sSf http://localhost:5000 > /dev/null; then
          echo "Webapp started successfully"
        else
          echo "Failed to start webapp"
          exit 1
        fi
        pkill -f 'dotnet run'
