name: .NET Build Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: List directory contents after checkout
      run: ls -la

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: List directory contents after setup
      run: ls -la

    # Restaurar dependências do .NET
    - name: Restore dependencies
      run: dotnet restore ./github4women/github4women.csproj

    - name: List directory contents after restore
      run: ls -la ./github4women

    # Build do projeto
    - name: Build the project
      run: dotnet build ./github4women/github4women.csproj --configuration Release --no-restore

    - name: List output directory contents after build
      run: ls -la ./github4women/bin

    - name: List output directory contents after build Release
      run: ls -la ./github4women/bin/Release

    - name: List net6.0 directory contents after build
      run: ls -la ./github4women/bin/Release/net6.0

    # Executar testes (script personalizado)
    - name: Run tests
      run: dotnet test ./github4women/github4women.csproj --no-restore --verbosity normal

    # Rodar o webapp e verificar se ele inicia corretamente
    - name: Start and verify webapp
      run: |
        echo "Starting webapp..."
        dotnet ./github4women/bin/Release/net6.0/github4women.dll --urls "http://localhost:5299" &
        sleep 10
        if curl -sSf http://localhost:5299 > /dev/null; then
          echo "Webapp started successfully"
        else
          echo "Failed to start webapp"
          exit 1
        fi
        pkill -f 'dotnet'
